In [111]:
# NumPy Extension 3 - Get all items between 3 and 7 from a and b and sum them together

import numpy as np 

a = np.arange (3,7).reshape (2,2) 
b = np.arange (3,7).reshape (2,2) 
c = np.dot(a, b)
e = np.sum(c,axis = 0)
print(e)



[74 92]


In [107]:
# Numpy Extension 2 - In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

import numpy as np

a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8, 9]
np.concatenate((a, b), axis=0)
np.unique(b)
print(b)

[4, 5, 6, 7, 8, 9]


In [61]:
# This is a test for NumPy Extension 1 - NOT PART OF HOME-LEARNING TASKS

import numpy as np
np.indices((4,4)) # how to make it start from 1 instead of 0?


array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [102]:
# NumPy Extension 1 - Create the following pattern without hardcoding. Use only NumPy functions.

import numpy as np
ones = np.ones((1,3))
twos = np.full((1, 3), 2)
threes = np.full((1, 3), 3)
incr = np.full((3,3),(1,2,3))

print(ones)
print(twos)
print(threes)
print(incr)


[[1. 1. 1.]]
[[2 2 2]]
[[3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
#  NumPy Task6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

import numpy as np
a = np.arange (1,10).reshape (3,3) 
b = np.arange (10,19).reshape (3,3) 
c = np.dot(a, b)
sum = np.sum(c)
print(a)
print(b)
print(c)
print(sum)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [34]:
# NumPy Task 5. Convert a 1D array to a 2D array with 2 rows

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newArray = array.reshape(2, 6) 
print(newArray)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
# NumPy Task 4. Replace all odd numbers in an array of 1-10 with the value -1

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_replace_odd = np.where(array%2 == 1, -1, array)
print(array_replace_odd)
   

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [38]:
# NumPy Task 3. Extract all odd numbers from array of 1-10

import numpy as np
array = np.arange(1, 10, 2) 
print(array)

[1 3 5 7 9]


In [90]:
# NumPy Task 2. Create a 3×3 NumPy array of all Boolean value Trues - AN ALTERNATIVE

import numpy as np

bool_arr = np.array([3, 3, 3, 3, 3, 3, 3, 3, True], dtype=bool) # not sure if this is how to make it 3x3
print(bool_arr.reshape(3, 3))



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [66]:
# NumPy Task 2. Create a 3×3 NumPy array of all Boolean value Trues

import numpy as np
array = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1,])
newArray = array.reshape(3, 3) 
print(newArray)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [35]:
# NumPy Task 1. Create a 1D array of numbers from 0 to 9

import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
# Task 2
# this program asks a student for their percentage mark and convert it to a grade, using a function called 'mark_grade'

def mark_grade(perc):
    if perc >= 90:
        return "A+"
    elif perc >= 80 and perc < 90:
        return "A"
    elif perc >= 70 and perc < 80:
        return "B"
    elif perc >= 60 and perc < 70:
        return "C"
    elif perc >= 50 and perc < 60:
        return "D"
    else:
        return "F"

mark = int(input("What was your mark (in percentage)?"))
grade = mark_grade(mark)

target = input("What grade did you want to achieve?")

if target == grade:
    print("Well done! You've achieved your target grade.")
    print("Your grade was", grade, "and you wanted to achieve", target)
elif target == "A+" and grade == "A":
    print("You were close!")
    print("Your grade was", grade, "and you wanted to achieve", target)
elif target == "A" and grade == "A+":
    print("Congrats! You received a grade higher than your aim.")
    print("Your grade was", grade, "and you wanted to achieve", target)
elif target < grade:
    print("Don't be discouraged. Just keep working.")
    print("Your grade was", grade, "and you wanted to achieve", target)
else:
    print("Congrats! You received a grade higher than your aim.")
    print("Your grade was", grade, "and you wanted to achieve", target)



Don't be discouraged. Just keep working.
Your grade was B and you wanted to achieve 80


In [44]:
# Task 1
# this program allows users to enter 4 numbers and stores them in a file called “Numbers”

# to write into the file:

my_file = open("Numbers.txt", "w")
my_file.write(str("Please enter the first number:"))
my_file.write("\n")
my_file.write(str("Please enter the second number:"))
my_file.write("\n")
my_file.write(str("Please enter the third number:"))
my_file.write("\n")
my_file.write(str("Please enter the fourth number:"))
my_file.write("\n")
my_file.close()


# to append to the file:

my_file = open("Numbers.txt", "a")
my_file.write(str("I want to append here."))
my_file.close()


# to read into the file:

with open("Numbers.txt", "r") as my_file:
    data = my_file.read().replace('\n', ',')
my_file.close()


